AdobeDocs/commerce-services

package.json, yarn.lock
This pull request bumps the aio-theme to v4.6.4, which added the commerce-service Algolia search index to the site.
According to the Devsite team, although the index exists in Algolia, results won't appear in site search until we update each repo. I can confirm that results don't currently appear on production, but I'm curious to see how bumping the theme in a single commerce repo affects search (if it all). 
When I run a local build of this branch, site search returns results from the commerce-services index. I suspect that merging this will make results from the commerce-services index available when searching from the commerce-services site only on production and not any other context, but I want to test that theory.
- #28
=> Bump aio-theme for search

src/pages/product-recommendations/index.md
Add [edition keyword](https://github.com/adobe/aio-theme#edition-keyword) metadata to Product Recommendations SDK.
#27 
While reviewing https://github.com/magento-commerce/devdocs/pull/3206, I noticed that the Product Recommendations topic has the [`ee_only: true`](https://github.com/magento-commerce/devdocs/pull/3206/files#diff-664c977119786d362cbffcda991da82889c5bddc5c0bb4787502b9a0f7e37f27R4) property set. This PR adds the equivalent property for devsite repos.
GitHub Actions PR validation
=> Add edition metadata for Product Recommendations SDK

src/pages/shared-services/storefront-events/collector/index.md
This pull request (PR) this adds specific event support by framework.
https://developer.adobe.com/commerce/services/shared-services/storefront-events/collector/#quick-start.
whatsnew
Added event support tables by framework to the [Adobe Commerce Event Framework](https://developer.adobe.com/commerce/services/shared-services/storefront-events/collector/#quick-start) topic.
=> [PREX-1524] Added events table to Events Collector topic

src/_includes/graphql/catalog-service/categories.md, src/_includes/graphql/catalog-service/headers.md, src/_includes/graphql/catalog-service/product-view.md, src/_includes/graphql/live-search-headers.md, src/data/navigation/header.js, src/data/navigation/sections/graphql.js, src/data/navigation/sections/index.js, src/pages/graphql/catalog-service/categories.md, src/pages/graphql/catalog-service/index.md, src/pages/graphql/catalog-service/product-search.md, src/pages/graphql/catalog-service/products.md, src/pages/graphql/catalog-service/refine-product.md, src/pages/graphql/index.md, src/pages/graphql/live-search/attribute-metadata.md, src/pages/graphql/live-search/index.md, src/pages/graphql/live-search/product-search.md, src/pages/graphql/recommendations/index.md, src/pages/graphql/recommendations/recommendations.md
This pull request (PR) migrates the Live Search, Catalog Service, and Product Recommendations GraphQL docs from the `commerce-webapi` repo to this repo. The only significant new content is in `src/pages/graphql/index.md`.
Staging: https://developer-stage.adobe.com/commerce/services/graphql/
- ...
- ...
=> COMDOX-804 Migrate Services GraphQL topics

.remarkrc.mjs, package.json, src/pages/live-search/index.md, src/pages/product-recommendations/index.md, src/pages/reporting/import-api.md, src/pages/reporting/libraries.md, src/pages/shared-services/storefront-events/collector/index.md, src/pages/shared-services/storefront-events/sdk/index.md, yarn.lock
This pull request (PR):
- Adds a plugin [remark-lint-no-dead-urls](https://github.com/remarkjs/remark-lint-no-dead-urls) to ensure that external URLs in Markdown pages are working. The linter returns warnings on https://www.php.net/ on working links in some reason (I assume server related issues) so I excluded this domain in the configuration.
- Replaces or removes dead links
Internal ticket: COMDOX-156
[Failed validate job](https://github.com/AdobeDocs/commerce-testing/actions/runs/6948160793/job/18903522012#step:11:12) reporting about dead links.
=> Add a linter to validate external links

src/_includes/graphql/catalog-service/product-view.md, src/pages/graphql/catalog-service/index.md, src/pages/graphql/catalog-service/products.md
Added customizable options field descriptions to product and refine product queries, and added the inputOptions data to the query and response output. 
- [products query](https://developer.adobe.com/commerce/services/graphql/catalog-service/products/)
- [refineProducts query](https://developer.adobe.com/commerce/services/graphql/catalog-service/products/)
To do:
https://git.corp.adobe.com/magento-datalake/catalog-storefront-api-service/pull/152
=> Add customizable options to Catalog Service schema 

package.json, src/pages/graphql/index.md, yarn.lock
This pull request (PR) upgrades theme to [v4.11.14](https://github.com/adobe/aio-theme/compare/%40adobe/gatsby-theme-aio%404.11.9...adobe/gatsby-theme-aio%404.11.14).
https://developer-stage.adobe.com/commerce/services/
=> Upgrade theme to v4.11.14

src/_includes/graphql/catalog-service/headers.md, src/pages/graphql/live-search/product-search.md
Add required `api-key` header value for Catalog Service productsearch query.
[productSearch Query](https://developer.adobe.com/commerce/services/graphql/live-search/product-search/)
=> Add required `api-key` value for Catalog Service productSearch query

src/_includes/graphql/catalog-service/headers.md, src/_includes/graphql/customer-group-code.md, src/pages/graphql/catalog-service/categories.md, src/pages/graphql/catalog-service/products.md, src/pages/graphql/catalog-service/refine-product.md, src/pages/graphql/live-search/product-search.md, src/pages/graphql/recommendations/recommendations.md
Updates description for `Magento-Customer-Group` header required for Catalog Service and Product Recommendations API requests.
[DATA-6141](https://jira.corp.adobe.com/browse/DATA-6141)
Preview of updated information rendered in the Required Header table and explanation of finding `customerGroupCode`.
- https://developer.adobe.com/commerce/services/graphql/catalog-service/products/#required-headers
- https://developer.adobe.com/commerce/services/graphql/recommendations/recommendations/#required-headers
- https://developer.adobe.com/commerce/services/graphql/live-search/product-search/#required-headers
=> Updates for Customer Group required header description

src/pages/graphql/catalog-service/categories.md, src/pages/graphql/catalog-service/refine-product.md
Fixes the include file reference that provides information about finding the customer group code for Catalog Service refine and products queries. 
https://developer.adobe.com/commerce/services/graphql/catalog-service/refine-product/
https://developer.adobe.com/commerce/services/graphql/catalog-service/products/
=> Fix include reference for Catalog Service topics

src/pages/graphql/live-search/product-search.md
This pull request (PR) adds a link to the boundaries and limits page in the live search guide.
- https://developer.adobe.com/commerce/services/graphql/live-search/product-search/
=> Adding link to live search guide

src/_includes/graphql/catalog-service/product-view.md
Update product view output fields to add `lastModifiedAt` and also add missing `ProductViewVideo` attribute.
- Document `lastModifiedDate`
- Add missing `ProductViewVideo` object and associated attributes
[products query](https://developer.adobe.com/commerce/services/graphql/catalog-service/products/)
[refineProducts query](https://developer.adobe.com/commerce/services/graphql/catalog-service/refine-product/)
[productsSearch query](https://developer.adobe.com/commerce/services/graphql/live-search/product-search/)
[variants query](https://developer.adobe.com/commerce/services/graphql/catalog-service/product-variants/)
=> Update ProductView object to add new schema fields - merge when CS v1.26 is released

.github/workflows/stage.yml
This pull request (PR) changes workflow to restrict the manual running of the Staging GH Action to the ccdm-publish-to-staging branch.
Internal ticket: COMDOX-1100
=> Run staging workflow only for the ccdm-publish-to-staging branch

.github/workflows/github-pages.yml, .gitignore
This pull request (PR) updates the github-pages workflow to allow deployments to the private GitHub Pages site.
_Disclaimer: This solution won't work for public Pages in private repos._
- none
=> Fix github-pages workflow in private repos

src/openapi/data-ingestion-schema-v1.yaml
This pull request (PR) updates "roles" attribute definition defined for product, product  images and attributes metadata APIs
- https://developer-stage.adobe.com/commerce/services/composable-catalog/data-ingestion/api-reference/
=> [CCDM] DCAT-2110: update "roles"

src/openapi/data-ingestion-schema-v1.yaml
This pull request (PR) created to update information about configurable product prices calculation
- https://developer-stage.adobe.com/commerce/services/composable-catalog/data-ingestion/api-reference/#operation/PricesPut
=> DCAT-2152: Price should not be persisted for Configurable Product type

spectaql/config-storefront.yml, spectaql/metadata-storefront.json, static/graphql-api/storefront-api/index.html
This pull request (PR) hides the "categories" query in the [Storefront API](https://developer-stage.adobe.com/commerce/services/composable-catalog/storefront-services/api-reference/) documentation. The categories data is not currently supported by the data ingestion API. 
- https://developer-stage.adobe.com/commerce/services/composable-catalog/storefront-services/api-reference/
https://commerce-docs.github.io/commerce-services/graphql-api/storefront-api/index.html#group-Operations-Queries
=> Hide the "categories" query

spectaql/comdox-theme/views/partials/graphql/_query-or-mutation-or-subscription.hbs, spectaql/comdox-theme/views/partials/graphql/type.hbs, spectaql/config-admin.yml, spectaql/config-storefront.yml, static/graphql-api/admin-api/index.html, static/graphql-api/storefront-api/index.html
This pull request (PR) adds 'back to top' hyperlink to GraphQL API reference at the end of each doc row for instant navigation to the top of the page which can be annoying for long pages via scrolling.
Related pull request: https://github.com/AdobeDocs/commerce-webapi/pull/394
- https://developer-stage.adobe.com/commerce/services/composable-catalog/data-ingestion/api-reference/
- https://developer-stage.adobe.com/commerce/services/composable-catalog/storefront-services/api-reference/
- https://commerce-docs.github.io/commerce-services/composable-catalog/admin/api-reference/
- https://commerce-docs.github.io/commerce-services/composable-catalog/storefront-services/api-reference/
=> Add 'back to top' to GraphQL API docs

src/openapi/data-ingestion-schema-v1.yaml, src/pages/composable-catalog/ccdm-use-case.md, src/pages/composable-catalog/data-ingestion/using-the-api.md
This pull request (PR) is to change the feed CCDM API to move tenantId to beginning of path
- https://developer-stage.adobe.com/commerce/services/composable-catalog/data-ingestion/api-reference/
=> DCAT-2283: Changing feed CCDM API to move tenantId to beginning of path

src/pages/cloud/guides/rest/index.md, src/pages/reference/cloud/rest.md
This PR removes the list of events/webhooks from ACCS docs and instead explains how to view a list of available events/webhooks in the Admin.
=> Simplifying  events/webhooks

src/@adobe/gatsby-theme-aio/components/Edition/index.js, src/pages/graphql/catalog-service/categories.md, src/pages/graphql/catalog-service/index.md, src/pages/graphql/catalog-service/product-variants.md, src/pages/graphql/catalog-service/products.md, src/pages/graphql/catalog-service/refine-product.md, src/pages/graphql/index.md, src/pages/graphql/live-search/attribute-metadata.md, src/pages/graphql/live-search/index.md, src/pages/graphql/live-search/product-search.md, src/pages/graphql/recommendations/index.md, src/pages/graphql/recommendations/recommendations.md, src/pages/live-search/index.md, src/pages/product-recommendations/index.md, src/pages/shared-services/storefront-events/collector/index.md, src/pages/shared-services/storefront-events/sdk/context.md, src/pages/shared-services/storefront-events/sdk/index.md, src/pages/shared-services/storefront-events/sdk/publish.md, src/pages/shared-services/storefront-events/sdk/subscribe.md, src/pages/shared-services/storefront-events/sdk/unsubscribe.md
This pull request (PR) aligns the PaaS edition tooltip with recent changes.
It also removes the `paas` edition from content that was formerly marked with the `ee` (Adobe Commerce only) edition.
=> Modify edition label for PaaS

src/openapi/data-ingestion-schema-v1.yaml
* Added documentation for price-book delete that all assigned prices will also get deleted
* https://developer-stage.adobe.com/commerce/services/composable-catalog/data-ingestion/api-reference/#operation/createProducts
* https://jira.corp.adobe.com/browse/DCAT-2205
=> DCAT-2205: Adding documentation for price-book delete that all assigned prices will also get deleted

src/openapi/data-ingestion-schema-v1.yaml
Reverts the changes to the `visibleIn` enum options of the Metadata endpoint to use:
```
enum:
- PRODUCT_DETAIL
- PRODUCT_LISTING
- SEARCH_RESULTS
- PRODUCT_COMPARE
```
Effectively reverts commit [e577d44](https://github.com/AdobeDocs/commerce-services/commit/e577d4458c520131ea49bd89135d47152ff4f4ae)
=> Revert changes to Metadata visibleIn enum options

src/pages/composable-catalog/ccdm-use-case.md, src/pages/graphql/index.md
Updates the Merchandising Services tutorial to add a note about using Channels and Policies UI instead of the APIs.
[Define the channel and policies](https://developer-stage.adobe.com/commerce/services/composable-catalog/ccdm-use-case/#step-2-define-the-channel-and-policies)
=> COMOPT-383: Use ComOpt UI for channels and policies

src/openapi/data-ingestion-schema-v1.yaml, src/pages/composable-catalog/ccdm-use-case.md, src/pages/composable-catalog/data-ingestion/index.md, src/pages/composable-catalog/index.md, src/pages/composable-catalog/manage-catalogs.md, src/pages/composable-catalog/storefront-services/using-the-api.md, static/graphql-api/storefront-api/index.html
- Rename field name scope to source for Product and ProductMetadata entities (DCAT-2454)
- Product attribute type field is not longer required (DCAT-2461)
- ...
- ...
=> DCAT-2454: Rename scope to source

src/pages/optimizer/data-ingestion/using-the-api.md
Add a reference to the Java SDK in the "Create integrations with SDK" section, alongside the existing TypeScript SDK. This provides visibility into both available SDKs for integrating with the Adobe Commerce Optimizer Data Ingestion API.
- https://developer.adobe.com/commerce/services/optimizer/data-ingestion/using-the-api/#create-integrations-with-sdk
=> Add link to Java SDK in SDK integration section

.github/workflows/stage.yml
This pull request (PR) reverts the staging deployment GitHub Actions workflow to trigger on workflow dispatch similar to other commerce devsite repos.
This is necessary to begin testing the REST API playground in #273 since the repo maintainer has requested to use `main` as the base branch for #273.
=> feat: change trigger to workflow dispatch for staging deployment
