src/data/navigation/header.js
src/data/navigation/sections/live_search.js
src/pages/index.md
src/pages/live-search/index.md

This PR migrates the Live Search events topic from devdocs to this repo.

Add Live Search topic

---

.github/linters/metadata.schema.yml
.remarkrc.mjs
package.json
src/pages/index.md
src/pages/live-search/index.md
src/pages/product-recommendations/catalog-saas-export-module.md
src/pages/product-recommendations/index.md
src/pages/reporting/export-api.md
src/pages/reporting/import-api.md
src/pages/reporting/index.md
src/pages/reporting/libraries.md
src/pages/shared-services/index.md
src/pages/shared-services/storefront-events/collector/index.md
src/pages/shared-services/storefront-events/index.md
src/pages/shared-services/storefront-events/sdk/context.md
src/pages/shared-services/storefront-events/sdk/index.md
src/pages/shared-services/storefront-events/sdk/publish.md
src/pages/shared-services/storefront-events/sdk/subscribe.md
src/pages/shared-services/storefront-events/sdk/unsubscribe.md
yarn.lock

This pull request (PR):
- Adds `keyword` metadata to enhance the site search experience for users (fcd6a66331769d6e58242b8b20c5a3469ef9f604).
- These keywords will appear as additional filters on the site search results page so that users can narrow the scope of what they're looking for.
- Keywords are defined in the `.github/linters/metadata.schema.yml` file.
- Keyword values map to the `exl-config/features.yml` metadata file that we use for Experience League repos for consistency.
- Adds a new PR validation test for the following metadata (93e6cb403abd9498c6c90191b46f23f14e69f6a9):
- `title:` is **required** and cannot exceed 60 characters (SEO)
- `description:` is **required** and cannot exceed 160 characters (SEO)
- `keywords:` is **optional**  and must match a defined value (site …

COMDOX-345: Add topic metadata and validation test

---

src/pages/shared-services/storefront-events/sdk/index.md

This pull request (PR) changes unpkg URL to use CDN. Also added code to confirm SDK downloaded successfully.
- https://developer.adobe.com/commerce/services/shared-services/storefront-events/sdk/

Update Event SDK Docs

---

src/pages/shared-services/storefront-events/collector/index.md

This pull request (PR) changs unpkg URL to use CDN.
- https://developer.adobe.com/commerce/services/shared-services/storefront-events/collector/

Update Event Collector Docs

---

src/pages/graphql/catalog-service/products.md
src/pages/graphql/index.md
src/pages/graphql/recommendations/recommendations.md

This pull request (PR) adds links to the API playground.
- ...
- ...

Add links to API playground

---

src/pages/graphql/live-search/product-search.md

This pull request (PR) moves the link for how to install the beta higher up on the page.
- https://developer.adobe.com/commerce/services/graphql/live-search/product-search/#filtering-using-search-capability

Moving link to installation higher up

---

src/pages/product-recommendations/catalog-saas-export-module.md
src/pages/reporting/export-api.md

This pull request (PR) replaces links to decommissioned resources with actual up-to-date links.
- https://developer.adobe.com/commerce/services/product-recommendations/catalog-saas-export-module/
- https://developer.adobe.com/commerce/services/reporting/export-api/

Replace links to decommissioned resources

---

src/pages/graphql/catalog-service/categories.md
src/pages/graphql/catalog-service/product-variants.md
src/pages/graphql/catalog-service/products.md
src/pages/graphql/catalog-service/refine-product.md

Apply code block formatting to request and response.
Apply code block formatting to request and response.
https://developer.adobe.com/commerce/services/graphql/catalog-service/categories/

Apply code block formatting

---

.github/workflows/stage.yml

This pull request (PR) updates the fixed branch name allowed for staging.

Update the branch name set for staging

---

src/openapi/data-ingestion-schema-v1.yaml

This pull request (PR) updates response object for CCDM APIs
- https://developer-stage.adobe.com/commerce/services/composable-catalog/data-ingestion/api-reference/

[CCDM] DCAT-2079 response object

---

.github/workflows/stage.yml

This pull request (PR) modifies the staging workflow to enable triggering on each push to `ccdm-early-access`.
none

Trigger staging workflow on each push to ccdm-early-access

---

src/pages/graphql/live-search/attribute-metadata.md

Replace the live search endpoint with the federated endpoint for catalog services.
JIRA: [MSRCH-4778](https://jira.corp.adobe.com/browse/MSRCH-4778)
[attributeMetadata query](https://developer.adobe.com/commerce/services/graphql/live-search/attribute-metadata/#endpoint)

MSRCH-4778: Update attribute-metadata.md with federated endpoint

---

src/openapi/data-ingestion-schema-v1.yaml

See https://jira.corp.adobe.com/browse/DCAT-2204
https://developer-stage.adobe.com/commerce/services/composable-catalog/data-ingestion/api-reference/

DCAT-2204: Replace the DELETE method with POST for CCDM

---

src/openapi/data-ingestion-schema-v1.yaml
src/pages/composable-catalog/ccdm-use-case.md
src/pages/composable-catalog/data-ingestion/using-the-api.md

Revert PR with updated path for data ingestion endpoints
Reverts AdobeDocs/commerce-services#200

Revert "DCAT-2283: Changing feed CCDM API to move tenantId to beginning of path"

---

src/pages/index.md

This pull request (PR) fixes a couple of small issues on the home page.
https://developer.adobe.com/commerce/services/

fix: home page

---

README.md
src/pages/graphql/index.md

This pull request (PR) adds info about using the shadowed edition component to the repo's README.

docs: add info about edition component

---

src/_includes/graphql/endpoints.md
src/pages/graphql/catalog-service/categories.md
src/pages/graphql/catalog-service/product-variants.md
src/pages/graphql/catalog-service/products.md
src/pages/graphql/catalog-service/refine-product.md
src/pages/graphql/live-search/attribute-metadata.md
src/pages/graphql/live-search/product-search.md

Replace per-file endpoints information with a single `endpoints` include file.
- Replace endpoint content in each file with include file reference.
- Add SaaS and PaaS badging for endpoints
JIRA: CCSAAS-2104

- In Catalog, LS, and PREX API references replace

---

spectaql/config-merchandising.yml
spectaql/config-storefront.yml
src/openapi/README.md
src/pages/optimizer/ccdm-use-case.md
src/pages/optimizer/data-ingestion/index.md
src/pages/optimizer/data-ingestion/using-the-api.md
src/pages/optimizer/merchandising-services/index.md
src/pages/optimizer/merchandising-services/use-cases.md
src/pages/optimizer/merchandising-services/using-the-api.md

Fix links in Dev Guide after navigation refactoring for references.

Fix broken links in dev guide

---

src/_includes/authentication/get-new-bearer-token.md
src/_includes/authentication/initial-auth-for-api-access.md

Update ACO authentication information to replace the Adobe I/O API card with ACO data ingestion card, and update scopes in auth token request.
[REST authentication](https://developer.adobe.com/commerce/services/optimizer/data-ingestion/authentication/)

Update initial-auth-for-api-access.md with ACO ingestion API config

---

src/pages/optimizer/data-ingestion/api-reference.md
src/pages/optimizer/data-ingestion/using-the-api.md
src/pages/reference/rest/index.md

Build the OpenAPI spec from the main branch.

Update Data Ingestion API

---

.github/workflows/stage.yml
package.json
src/pages/optimizer/data-ingestion/api-reference.md
src/pages/optimizer/data-ingestion/using-the-api.md
src/pages/reference/rest/index.md
yarn.lock

Update develop branch

---

src/_includes/authentication/get-tenant-id.md
src/pages/credential/GetCredentialOAuthS2s.js
src/pages/optimizer/admin/using-the-api.md
src/pages/optimizer/data-ingestion/using-the-api.md
src/pages/optimizer/merchandising-services/troubleshooting.md
src/pages/optimizer/merchandising-services/using-the-api.md

This pull request (PR) normalizes references to tenant ID. To match what is in the product UI, we should replace with "instance ID".

Replace tenant ID with instance ID

---

src/pages/optimizer/data-ingestion/using-the-api.md

Fix endpoint. 
https://developer.adobe.com/commerce/services/optimizer/data-ingestion/using-the-api/#make-your-first-request

Update API endpoint for product metadata creation

---

src/pages/optimizer/data-ingestion/using-the-api.md

Updated section title to clarify SDK integration.
- https://developer.adobe.com/commerce/services/optimizer/data-ingestion/using-the-api/#create-integrations-with-sdk

Revise SDK integration section heading
